import type { TokenTable } from "../model/types.js";

const CATEGORY_TO_THEME_KEY = {
  spacing: "spacing",
  radius: "borderRadius",
  fontSize: "fontSize",
  color: "colors",
} as const;

/** Renders the tokens minted in pass 1 as a `theme.extend` fragment the reconciled HTML depends on. */
export function renderTailwindConfigModule(tokens: TokenTable): string {
  const extend: Record<string, Record<string, string>> = {};

  for (const [category, themeKey] of Object.entries(CATEGORY_TO_THEME_KEY)) {
    const generated = tokens.generated[category as keyof TokenTable["generated"]];
    if (generated.length === 0) continue;
    extend[themeKey] = Object.fromEntries(generated.map((token) => [token.key, token.value]));
  }

  return `/** Generated by windtailor — tokens minted from values that didn't fit Tailwind's stock scale. */
module.exports = {
  theme: {
    extend: ${JSON.stringify(extend, null, 2).replace(/\n/g, "\n    ")},
  },
};
`;
}
